services:
  backend:
    volumes:
      - static:/static
    build:
      context: ./backend
    ports:
      - "8000:8000"
    
  frontend:
    build: 
      context: ./frontend
    volumes:
      - frontend:/app/build
    ports:
      - "3000:3000"
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=vphrase
  #     - POSTGRES_PASSWORD=vphrase_db_pass
  #     - POSTGRES_DB=vphrase_db
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/client
    ports:
      - "80:80"


volumes:
  static:
  frontend:
  # postgres_data: