# Generated by Django 5.0.7 on 2024-07-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movieactor_id_alter_moviegenre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
