# Generated by Django 5.0.7 on 2024-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_id_alter_movieactor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='grossing_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
