# Generated by Django 5.0.7 on 2024-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_movie_grossing_value_alter_movie_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.SmallIntegerField(null=True),
        ),
    ]
