# Generated by Django 5.0.7 on 2024-07-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_moviedirector_remove_movie_director_movie_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(null=True, to='api.moviedirector'),
        ),
    ]
