# Generated by Django 5.0.7 on 2024-07-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_movie_directors_movie_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
    ]
