# Generated by Django 5.0.7 on 2024-07-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_movie_runtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieActor',
        ),
        migrations.DeleteModel(
            name='MovieDirector',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
